apiVersion: v1
kind: ServiceAccount
metadata:
  name: hardened-nginx
  namespace: hardened-nginx
  labels:
    app.kubernetes.io/name: hardened-nginx
    app.kubernetes.io/instance: hardened-nginx
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: hardened-nginx
automountServiceAccountToken: false
